DELETE http://localhost:3001/api/persons/62a0cba2a8664910a83936cb

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Edward Chung 123",
    "number": "0123456789"
}

###
GET http://localhost:3001/api/persons

###
PUT http://localhost:3001/api/persons/2a0fe47720bf97fd8896311
content-type: application/json

{
    "name": "Edward",
    "number": "0123456789"
}